# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: azuremessage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61zuremessage.proto\x12\x0c\x61zuremessage"`\n\x0c\x41zureMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0csubscription\x18\x03 \x01(\t\x12\x0b\n\x03sku\x18\x04 \x01(\t\x12\x13\n\x0breservation\x18\x05 \x01(\t"E\n\x11\x41zureMessageStack\x12\x30\n\x0c\x61zuremessage\x18\x01 \x03(\x0b\x32\x1a.azuremessage.AzureMessage'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "azuremessage_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_AZUREMESSAGE"]._serialized_start = 36
    _globals["_AZUREMESSAGE"]._serialized_end = 132
    _globals["_AZUREMESSAGESTACK"]._serialized_start = 134
    _globals["_AZUREMESSAGESTACK"]._serialized_end = 203
# @@protoc_insertion_point(module_scope)
